/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_dynamodb_all_tables_region": "eu-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "dynamoBbaas-dev",
            "region": "eu-west-2"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "apibbaas",
            "endpoint": "https://0869wgq0le.execute-api.eu-west-2.amazonaws.com/dev",
            "region": "eu-west-2"
        }
    ],
    "aws_cognito_identity_pool_id": "eu-west-2:85cb0e36-a94f-422f-beee-34543d783b0b",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_LjnXTpgkP",
    "aws_user_pools_web_client_id": "2ebl8cabcha5t99pg7ormu0pna",
    "oauth": {}
};


export default awsmobile;
